eureka:
client:
serviceUrl:
defaultZone: http://eureka-primary:8761/eureka,http://eureka-secondary:8762/eureka
---
spring:
  profiles: lazy
activities: activity-lazy-1
---
spring:
  profiles: crazy
activities: activity-crazy-1